version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/documentos:/app/documentos
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"
    restart: unless-stopped